spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/sigaplusdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: SAGR0814
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8081