name: CD
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: sagr2003/sigaplus
          tags: ${{ secrets.APP_VERSION }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Update Version Number
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'APP_VERSION'
          value: $((${{ secrets.APP_VERSION }} + 1))
          repository: sagr2003/siga-plus
          token: ${{ secrets.SIGAPLUS_TOKEN}}